#### 1. Write a program to create a 5 dimentional array with all zeros and ones.

In [1]:
import numpy as np

In [13]:
np.zeros((1,1,1,5,4))

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]]])

In [14]:
np.ones((1,1,1,5,4))

array([[[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]]])

#### 2. Write a program to create an array of 10 zeros, 10 ones, 10 fives in row 1,2,3. which create a new array of shape(3,10) 

In [15]:
a = np.zeros(10,dtype=int),np.ones(10,dtype=int),np.full(10,5)
print("shape of array : ",np.shape(a))
a

shape of array :  (3, 10)


(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5]))

#### 3. Write a program to create a 3x4 matric filled with values from 10 to 21 

In [17]:
np.arange(10,22).reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

#### 4. Write a program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9

In [20]:
np.diag(np.arange(1,10))

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

#### 5. Write a program to create 4x4 array.Create an array from below array by swaping first and last,second and third colums.

In [37]:
a = np.array([np.arange(1,17)]).reshape(4,4)
print(a)
a[:,::-1]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

#### 6. Write a program to reverse an array (the first element becomes the last).Given array:[12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27]

In [39]:
a = np.array([12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27])
a[::-1]

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

#### 7. Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10,10. Elements range from 1 to 100

In [44]:
a = np.arange(1,101).reshape(10,10)
a[(a>30) & (a<80) & (a%5 == 0)]

array([35, 40, 45, 50, 55, 60, 65, 70, 75])

#### 8. Write a program to create a 2D array with 1 on the border and 0 inside.

In [53]:
a= np.ones((5,5),dtype = int)
a[1:-1,1:-1]=0
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### 9. Write a program to create a checkerboard pattern.Don't use default array function

In [58]:
a = np.ones((8,8), dtype=int)
for i in range(len(a)):
    if i % 2 == 0:
        (a[i])[::2]=0
    else:
        (a[i])[1::2]
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

#### 10. Write a program to find common values between two arrays

In [59]:
a = np.array([10,20,30,40,50])
b = np.array([70,60,30,40,50])
np.intersect1d(a,b)

array([30, 40, 50])

#### 11. Write a program to create an 2D array then reshape to 1D array

In [79]:
a = np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [74]:
#method_1
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [75]:
#method_2
a.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [86]:
#method_3
a.reshape(16)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [87]:
#method_4
a.reshape(16,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

#### 12. Write a user defined function for creating 1D or 2D without using array functions

In [1]:
def array():
    array = int(input("Enter 1D or 2D array :  "))
    if array ==2:
        function = (input("Enter number : "))
        function = " "+function
        a = int(input("Enter number of rows : "))
        b = int(input("Enter number of colums : "))
        if b == 0:
            print(a*function)
        else:
            print("array")
            for i in range(a):
                print(b*function)
            
    elif array == 1:
        function = (input("Enter number : "))
        function = " "+function
        a = int(input("Enter number of elements: "))
        print("array")
        return(a*function)
    else:
        print("Please Enter valid input")

In [4]:
array()

Enter 1D or 2D array :  2
Enter number : 16
Enter number of rows : 4
Enter number of colums : 4
array
 16 16 16 16
 16 16 16 16
 16 16 16 16
 16 16 16 16


In [2]:
array()

Enter 1D or 2D array :  1
Enter number : 1
Enter number of elements: 8
array


' 1 1 1 1 1 1 1 1'